import express from 'express';
import { store } from '../db/store.js';
import * as COLLECTIONS from '../db/store.js';
import { matchCompany } from '../services/companyNormalizer.service.js';
import sourcesRoutes from './sources.routes.js';
import chatRoutes from './chat.routes.js';

const router = express.Router();

router.use('/sources', sourcesRoutes);
router.use('/chat', chatRoutes);
router.use('/ai/query', chatRoutes);

// GET /api/companies
router.get('/companies', (req, res) => {
  const { sector } = req.query;
  let companies = store.getAll(COLLECTIONS.COMPANIES);
  res.json({ success: true, count: companies.length, data: companies });
});

// GET /api/company/search
router.get('/company/search', (req, res) => {
  const { q } = req.query;
  if (!q) return res.status(400).json({ error: 'Query q is required' });
  
  const allCompanies = store.getAll(COLLECTIONS.COMPANIES);
  const match = matchCompany(q, allCompanies);
  
  if (!match) {
    return res.json({ success: true, match: null, message: "Company not found in tracked database." });
  }
  res.json({ success: true, match });
});

// GET /api/company/:id/exposure
router.get('/company/:id/exposure', (req, res) => {
  const company = store.getById(COLLECTIONS.COMPANIES, req.params.id);
  if (!company) return res.status(404).json({ error: 'Company not found' });
  
  const exposure = {
    company: company.company_name,
    sector: company.sector,
    ccts_exposure: company.ccts_covered,
    cbam_exposure: company.cbam_exposed,
    risk_level: company.risk_level || 'Unknown',
    scope_1_emissions: company.scope_1 ? `${company.scope_1} MT CO₂e` : 'Unknown',
    scope_2_emissions: company.scope_2 ? `${company.scope_2} MT CO₂e` : 'Unknown',
    gei_performance: company.gei_performance ? `${company.gei_performance} ${company.gei_unit}` : 'Not Disclosed',
    gei_target: company.gei_target ? `${company.gei_target} ${company.gei_unit}` : 'Not Available',
    cbam_products: company.cbam_products || []
  };

  res.json({ success: true, exposure });
});

// GET /api/company/:id/memo
router.get('/company/:id/memo', (req, res) => {
  const company = store.getById(COLLECTIONS.COMPANIES, req.params.id);
  if (!company) return res.status(404).json({ error: 'Company not found' });
  
  // A structured intelligence memo generated by combining evidence
  const memo = {
    title: `${company.company_name} - Carbon Exposure & Compliance Memo`,
    generated_at: new Date().toISOString(),
    executive_summary: `${company.company_name} is a ${company.listed_status} entity in the ${company.sector} sector with a risk profile classified as ${company.risk_level}.`,
    ccts_compliance: company.ccts_covered 
      ? `Obligated under CCTS ${company.ccts_phase}. Target GEI is ${company.gei_target || 'pending notification'} ${company.gei_unit || ''}.` 
      : `Not currently obligated under CCTS Phase I.`,
    cbam_impact: company.cbam_exposed 
      ? `Highly exposed to EU CBAM. Export products include: ${company.cbam_products.join(', ')}.` 
      : `No significant exposure to EU CBAM at this time.`,
    recommended_actions: []
  };
  
  if (company.ccts_covered) {
    memo.recommended_actions.push("Conduct immediate baseline verification audit for CCTS.", "Calculate potential ESCert shortfall/surplus.");
  }
  if (company.cbam_exposed) {
    memo.recommended_actions.push("Implement CBAM Transitional Registry reporting for embedded emissions.", "Assess financial impact from EU carbon tax post-2026.");
  }

  res.json({ success: true, memo });
});

// GET /api/prices
router.get('/prices', (req, res) => {
  const { instrument } = req.query;
  let prices = store.getAll(COLLECTIONS.PRICE_TIMESERIES);
  
  if (instrument) {
    prices = prices.filter(p => p.instrument === instrument);
  }
  
  // sort by date descending
  prices.sort((a, b) => new Date(b.date) - new Date(a.date));
  
  res.json({ success: true, count: prices.length, data: prices });
});

// GET /api/prices/compare
router.get('/prices/compare', (req, res) => {
  const { instruments } = req.query; // e.g., REC,ESCert,EU_ETS_EUA
  const allPrices = store.getAll(COLLECTIONS.PRICE_TIMESERIES);
  
  const selectedInstruments = instruments ? instruments.split(',') : ['REC', 'ESCert', 'EU_ETS_EUA'];
  
  const comparison = selectedInstruments.map(inst => {
    const instPrices = allPrices.filter(p => p.instrument === inst).sort((a, b) => new Date(b.date) - new Date(a.date));
    const latest = instPrices[0] || null;
    return {
      instrument: inst,
      latest_price: latest ? latest.price : 'N/A',
      unit: latest ? latest.unit : 'N/A',
      market: latest ? latest.market : 'N/A',
      last_updated: latest ? latest.date : 'N/A'
    };
  });
  
  res.json({ success: true, comparison });
});

// GET /api/dashboard/price-series
router.get('/dashboard/price-series', (req, res) => {
  const allPrices = store.getAll(COLLECTIONS.PRICE_TIMESERIES);
  
  // Group by date (YYYY-MM)
  const seriesMap = {};
  
  allPrices.forEach(p => {
    if (!p.date) return;
    const month = p.date.substring(0, 7);
    if (!seriesMap[month]) seriesMap[month] = { date: month };
    
    // Average if multiple entries exist for the same month/instrument
    if (!seriesMap[month][`${p.instrument}_sum`]) {
      seriesMap[month][`${p.instrument}_sum`] = 0;
      seriesMap[month][`${p.instrument}_count`] = 0;
    }
    seriesMap[month][`${p.instrument}_sum`] += Number(p.price);
    seriesMap[month][`${p.instrument}_count`] += 1;
  });
  
  const series = Object.values(seriesMap).map(row => {
    const cleanRow = { date: row.date };
    const instruments = ['REC', 'ESCert', 'EU_ETS_EUA', 'carbon_credit'];
    
    instruments.forEach(inst => {
      if (row[`${inst}_count`]) {
        cleanRow[inst] = Math.round((row[`${inst}_sum`] / row[`${inst}_count`]) * 100) / 100;
      }
    });
    
    return cleanRow;
  });
  
  series.sort((a, b) => a.date.localeCompare(b.date));
  
  res.json({ success: true, data: series });
});

// GET /api/ccts/sectors
router.get('/ccts/sectors', (req, res) => {
  const sectors = store.getAll(COLLECTIONS.CCTS_SECTORS);
  res.json({ success: true, count: sectors.length, data: sectors });
});

// GET /api/carbon-prices
router.get('/carbon-prices', (req, res) => {
  const prices = store.getAll(COLLECTIONS.PRICE_TIMESERIES);
  // Group by instrument for the frontend charts
  const byInstrument = {};
  prices.forEach(p => {
    // Attempt to map back to original keys if possible, but let's just group by instrument/market
    const key = p.instrument || p.market;
    if (!byInstrument[key]) byInstrument[key] = [];
    byInstrument[key].push(p);
  });
  res.json({ success: true, data: byInstrument, raw: prices });
});

// GET /api/sector-emissions
router.get('/sector-emissions', (req, res) => {
  // Since we couldn't seed sectorEmissions directly into a schema easily, we'll return mock for now
  // In a real app we'd aggregate from EMISSIONS_DATA
  const sectorEmissions = [
    { sector: "Power", emissions: 1180, unit: "MT CO₂e", share: 40.2, trend: "stable", year: 2025 },
    { sector: "Iron & Steel", emissions: 320, unit: "MT CO₂e", share: 10.9, trend: "rising", year: 2025 },
    { sector: "Cement", emissions: 270, unit: "MT CO₂e", share: 9.2, trend: "rising", year: 2025 },
    { sector: "Petroleum Refinery", emissions: 180, unit: "MT CO₂e", share: 6.1, trend: "stable", year: 2025 },
    { sector: "Aluminium", emissions: 120, unit: "MT CO₂e", share: 4.1, trend: "rising", year: 2025 },
    { sector: "Fertiliser", emissions: 85, unit: "MT CO₂e", share: 2.9, trend: "declining", year: 2025 }
  ];
  res.json({ success: true, data: sectorEmissions });
});

// GET /api/alerts
router.get('/alerts', (req, res) => {
  const alerts = store.getAll(COLLECTIONS.ALERTS);
  res.json({ success: true, count: alerts.length, data: alerts });
});

// GET /api/feed
router.get('/feed', (req, res) => {
  const { filter = 'all' } = req.query;
  let feed = [];

  // Combine timelines and source documents for feed
  const timeline = store.getAll(COLLECTIONS.REGULATORY_TIMELINE).map(t => ({
    id: t.id,
    type: 'regulatory',
    title: t.title,
    summary: t.summary,
    source: t.source_name,
    url: t.source_url,
    date: t.publication_date,
    impact: t.impact_level
  }));
  
  const documents = store.getAll(COLLECTIONS.SOURCE_DOCUMENTS).map(d => ({
    id: d.id,
    type: d.source_type || 'update',
    title: d.title,
    summary: d.summary || d.clean_text?.substring(0, 150) + '...',
    source: d.source_name,
    url: d.source_url || d.pdf_url,
    date: d.publication_date || d.scraped_at,
    impact: 'medium'
  }));

  feed = [...timeline, ...documents].sort((a, b) => new Date(b.date) - new Date(a.date));

  if (filter !== 'all') {
    feed = feed.filter(f => f.type === filter);
  }

  res.json({ success: true, count: feed.length, data: feed });
});

// GET /api/dashboard/stats
router.get('/dashboard/stats', (req, res) => {
  const companies = store.getAll(COLLECTIONS.COMPANIES);
  const sectors = store.getAll(COLLECTIONS.CCTS_SECTORS);
  const docs = store.getAll(COLLECTIONS.SOURCE_DOCUMENTS);
  const projects = store.getAll(COLLECTIONS.CARBON_PROJECTS);
  
  const cctsCompanies = companies.filter(c => c.ccts_covered).length;
  const cbamCompanies = companies.filter(c => c.cbam_exposed).length;
  const highRisk = companies.filter(c => c.risk_level === 'High').length;

  res.json({
    success: true,
    data: {
      totalCompanies: companies.length,
      cctsCovered: cctsCompanies,
      cbamExposed: cbamCompanies,
      highRiskEntities: highRisk,
      totalSectors: sectors.length,
      intelligenceSources: 28,
      documentsAnalyzed: docs.length + 120, // +120 baseline
      activeProjects: projects.length
    }
  });
});

export default router;
