export const SOURCE_TIERS = {
  A: 'Primary regulatory and official government sources — highest authority',
  B: 'Mandatory corporate disclosures (BRSR, annual reports, exchange filings)',
  C: 'Registries, exchanges, and market infrastructure — transactional data',
  D: 'Research bodies, standards organizations, and media',
  E: 'User-uploaded or unverified third-party data',
};

export const SOURCES = {
  bee: {
    name: 'Bureau of Energy Efficiency',
    url: 'https://beeindia.gov.in',
    tier: 'A',
    category: 'regulatory',
    jurisdiction: 'India',
    schedule: '6h',
    enabled: true,
  },
  moefcc: {
    name: 'Ministry of Environment, Forest and Climate Change',
    url: 'https://moef.gov.in',
    tier: 'A',
    category: 'regulatory',
    jurisdiction: 'India',
    schedule: '6h',
    enabled: true,
  },
  egazette: {
    name: 'e-Gazette of India',
    url: 'https://egazette.gov.in',
    tier: 'A',
    category: 'regulatory',
    jurisdiction: 'India',
    schedule: '6h',
    enabled: true,
  },
  pib: {
    name: 'Press Information Bureau',
    url: 'https://pib.gov.in',
    tier: 'A',
    category: 'regulatory',
    jurisdiction: 'India',
    schedule: '6h',
    enabled: true,
  },
  cerc: {
    name: 'Central Electricity Regulatory Commission',
    url: 'https://cercind.gov.in',
    tier: 'A',
    category: 'regulatory',
    jurisdiction: 'India',
    schedule: '6h',
    enabled: true,
  },
  icm_grid: {
    name: 'ICM Portal / Grid Controller',
    url: 'https://posoco.in',
    tier: 'C',
    category: 'registry',
    jurisdiction: 'India',
    schedule: '12h',
    enabled: true,
  },
  rec_registry_india: {
    name: 'REC Registry India',
    url: 'https://www.recregistryindia.nic.in',
    tier: 'C',
    category: 'registry',
    jurisdiction: 'India',
    schedule: '12h',
    enabled: true,
  },
  iex: {
    name: 'Indian Energy Exchange',
    url: 'https://www.iexindia.com',
    tier: 'C',
    category: 'exchange',
    jurisdiction: 'India',
    schedule: '6h',
    enabled: true,
  },
  pxil: {
    name: 'Power Exchange India Limited',
    url: 'https://www.pxil.com',
    tier: 'C',
    category: 'exchange',
    jurisdiction: 'India',
    schedule: '6h',
    enabled: true,
  },
  nse_brsr: {
    name: 'NSE BRSR Filings',
    url: 'https://www.nseindia.com',
    tier: 'B',
    category: 'company_disclosure',
    jurisdiction: 'India',
    schedule: '24h',
    enabled: true,
  },
  nse_annual_reports: {
    name: 'NSE Annual Reports',
    url: 'https://www.nseindia.com',
    tier: 'B',
    category: 'company_disclosure',
    jurisdiction: 'India',
    schedule: '24h',
    enabled: true,
  },
  bse_filings: {
    name: 'BSE Filings',
    url: 'https://www.bseindia.com',
    tier: 'B',
    category: 'company_disclosure',
    jurisdiction: 'India',
    schedule: '24h',
    enabled: true,
  },
  dgft: {
    name: 'DGFT Trade Data',
    url: 'https://www.dgft.gov.in',
    tier: 'B',
    category: 'trade',
    jurisdiction: 'India',
    schedule: '24h',
    enabled: true,
  },
  eu_cbam: {
    name: 'EU CBAM Portal',
    url: 'https://taxation-customs.ec.europa.eu/carbon-border-adjustment-mechanism_en',
    tier: 'A',
    category: 'regulatory',
    jurisdiction: 'EU',
    schedule: '12h',
    enabled: true,
  },
  eex: {
    name: 'European Energy Exchange',
    url: 'https://www.eex.com',
    tier: 'C',
    category: 'exchange',
    jurisdiction: 'EU',
    schedule: '6h',
    enabled: true,
  },
  unfccc: {
    name: 'United Nations Framework Convention on Climate Change',
    url: 'https://unfccc.int',
    tier: 'A',
    category: 'regulatory',
    jurisdiction: 'Global',
    schedule: '12h',
    enabled: true,
  },
  icap: {
    name: 'International Carbon Action Partnership',
    url: 'https://icapcarbonaction.com',
    tier: 'D',
    category: 'research',
    jurisdiction: 'Global',
    schedule: '24h',
    enabled: true,
  },
  world_bank_carbon: {
    name: 'World Bank Carbon Pricing Dashboard',
    url: 'https://carbonpricingdashboard.worldbank.org',
    tier: 'D',
    category: 'research',
    jurisdiction: 'Global',
    schedule: '24h',
    enabled: true,
  },
  verra: {
    name: 'Verra VCS Registry',
    url: 'https://registry.verra.org',
    tier: 'C',
    category: 'registry',
    jurisdiction: 'Global',
    schedule: '12h',
    enabled: true,
  },
  gold_standard: {
    name: 'Gold Standard Registry',
    url: 'https://registry.goldstandard.org',
    tier: 'C',
    category: 'registry',
    jurisdiction: 'Global',
    schedule: '12h',
    enabled: true,
  },
  cdm: {
    name: 'CDM Registry',
    url: 'https://cdm.unfccc.int',
    tier: 'C',
    category: 'registry',
    jurisdiction: 'Global',
    schedule: '12h',
    enabled: true,
  },
  gcc: {
    name: 'Global Carbon Council',
    url: 'https://www.globalcarboncouncil.com',
    tier: 'C',
    category: 'registry',
    jurisdiction: 'Global',
    schedule: '24h',
    enabled: true,
  },
  plan_vivo: {
    name: 'Plan Vivo',
    url: 'https://www.planvivo.org',
    tier: 'C',
    category: 'registry',
    jurisdiction: 'Global',
    schedule: '24h',
    enabled: true,
  },
  art_trees: {
    name: 'ART TREES',
    url: 'https://www.artredd.org',
    tier: 'C',
    category: 'registry',
    jurisdiction: 'Global',
    schedule: '24h',
    enabled: true,
  },
  icvcm: {
    name: 'Integrity Council for the Voluntary Carbon Market',
    url: 'https://icvcm.org',
    tier: 'D',
    category: 'standards',
    jurisdiction: 'Global',
    schedule: '24h',
    enabled: true,
  },
  vcmi: {
    name: 'Voluntary Carbon Markets Integrity Initiative',
    url: 'https://vcmintegrity.org',
    tier: 'D',
    category: 'standards',
    jurisdiction: 'Global',
    schedule: '24h',
    enabled: true,
  },
  sbti: {
    name: 'Science Based Targets initiative',
    url: 'https://sciencebasedtargets.org',
    tier: 'D',
    category: 'standards',
    jurisdiction: 'Global',
    schedule: '24h',
    enabled: true,
  },
  ceew: {
    name: 'Council on Energy, Environment and Water',
    url: 'https://www.ceew.in',
    tier: 'D',
    category: 'research',
    jurisdiction: 'India',
    schedule: '24h',
    enabled: true,
  },
  ieta: {
    name: 'International Emissions Trading Association',
    url: 'https://www.ieta.org',
    tier: 'D',
    category: 'research',
    jurisdiction: 'Global',
    schedule: '24h',
    enabled: true,
  },
  carboncredits_com: {
    name: 'CarbonCredits.com',
    url: 'https://carboncredits.com',
    tier: 'D',
    category: 'media',
    jurisdiction: 'Global',
    schedule: '24h',
    enabled: true,
  },
  ghg_protocol: {
    name: 'GHG Protocol',
    url: 'https://ghgprotocol.org',
    tier: 'D',
    category: 'standards',
    jurisdiction: 'Global',
    schedule: '24h',
    enabled: true,
  },
};
